version: "3.8"

services:
  cvgen-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    container_name: cv-gen-backend
    volumes:
      - ./:/app:cached
    command: air
    ports:
      - "5868:5864"
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    networks:
      - cv-generator-network