version: '3.8'

services:
  nginx:
    image: nginx
    container_name: cv-generator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - cv-generator-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cv-generator-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin0981234532adm
    networks:
      - cv-generator-network

  minio:
    image: minio/minio
    container_name: cv-generator-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadminadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - cv-generator-network

volumes:
  minio_data:
    driver: local

networks:
  cv-generator-network:
    external: true