version: '3.8'

services:
  nginx:
    image: nginx
    container_name: cv-generator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - cv-generator-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cv-generator-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin0981234532adm
    networks:
      - cv-generator-network

networks:
  cv-generator-network:
    external: true