version: '3.8'

services:
  nginx:
    image: nginx
    container_name: cv-generator-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - cv-generator-network

networks:
  cv-generator-network:
    external: true