version: "3.9"

services:
  loki:
    image: grafana/loki:latest
    container_name: cv-generator-loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - cv-generator-network

  promtail:
    image: grafana/promtail:latest
    container_name: cv-generator-promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - cv-generator-network

  grafana:
    image: grafana/grafana:latest
    container_name: cv-generator-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - cv-generator-network

networks:
  cv-generator-network:
    external: true