version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: cvuser-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cv-generator-network

  redis:
    container_name: cvuser-redis
    hostname: redis
    image: redis:latest
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - cv-generator-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: cvuser-backend
    ports:
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    volumes:
      - ./:/app:cached
    depends_on:
      - db
      - redis
    environment:
      REDIS_ADDRESS: redis:6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      GIN_MODE: "release"
    restart: always
    networks:
      - cv-generator-network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  cv-generator-network:
    external: true