version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    container_name: cvgatway-backend
    volumes:
      - ./:/app:cached
    command: air
    ports:
      - "5865:5864"
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    networks:
      - cv-generator-network

  # @TODO: remove this before deploy
#  redoc:
#    environment:
#      SPEC_URL: "http://localhost:8000/documentation/openapi.json"
#    networks:
#      - cv-generator-network