version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: cvgatway-backend
    ports:
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    volumes:
      - ./:/app:cached
    environment:
      GIN_MODE: "release"
    restart: unless-stopped
    networks:
      - cv-generator-network

  redoc:
    image: redocly/redoc
    container_name: cvgatway-redoc
    environment:
      SPEC_URL: /documentation/openapi.json
    volumes:
      - ./config/swagger/openapi.json:/usr/share/nginx/html/docs/openapi.json
    ports:
      - "8082:80"
    networks:
      - cv-generator-network

networks:
  cv-generator-network:
    external: true