version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: cvgatway-backend
    ports:
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    volumes:
      - ./:/app:cached
    environment:
      GIN_MODE: "release"
    restart: always
    networks:
      - cv-generator-network

networks:
  cv-generator-network:
    external: true